api/urls.py
from django.urls import path

from .views import get_room as api_get_room
from .views import get_rooms as api_get_rooms
from .views import get_routes as api_get_routes

urlpatterns = [
    path('', api_get_routes, name='api_get_routes'),

    path('rooms/', api_get_rooms, name='api_get_rooms'),
    path('rooms/<str:pk>', api_get_room, name='api_get_room'),
]

pairup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('base.urls')),
    path('rooms/', include('rooms.urls')),
    path('topics/', include('topics.urls')),
    path('activity/', include('activity.urls')),
    path('delete/', include('deletion.urls')),

    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

topics/urls.py
from django.urls import path

from .views import topics_page

urlpatterns = [
    path('', topics_page, name='topics_page')
]

base/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True)
    avatar = models.ImageField(null=True, default="/avatar.svg")
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


class Topic(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-updated", "-created"]

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-updated", "-created"]

    def __str__(self):
        return self.body

topics/views.py
from django.shortcuts import render

from base.models import Topic, Room


def topics_page(request):
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    topics = Topic.objects.filter(name__icontains=q)
    rooms = Room.objects.all()

    context = {
        'topics': topics,
        'rooms': rooms
    }

    return render(request, 'topics.html', context)

topics/templates/topics.html
{% extends 'main.html' %}

{% block content %}

    <main class="create-room layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'base_home' %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                                ></path>
                            </svg>
                        </a>
                        <h3>Browse Topics</h3>
                    </div>
                </div>

                <div class="topics-page layout__body">
                    <form action="" method="GET" class="header__search">
                        <label>
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>search</title>
                                <path
                                        d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                                ></path>
                            </svg>
                            <input name="q" placeholder="Search for topics"/>
                        </label>
                    </form>

                    <ul class="topics__list">
                        <li>
                            <a href="{% url 'topics_page' %}" class="active">All <span>{{ rooms.count }}</span></a>
                        </li>
                        {% for topic in topics %}
                            <li>
                                <a href="{% url 'base_home' %}?q={{ topic.name }}"> {{ topic.name }}
                                    <span>{{ topic.room_set.all.count }}</span></a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </main>

{% endblock %}